### ISSUE TITLE
请教一些差异性问题

### ISSUE THREAD

**Issue by Free-Qi** [chenshuai2144/pro-server#1]
陈帅先生您好， 我从antd design pro官网下载的项目和您写的pro-server项目有些差异，差异表现在右侧有个控制按钮，请问这是您自己添加的？还是antd design pro官方就给提供的？如果是您自己添加的可否提供源码供参考？

**Comment by chenshuai2144** [comment]
v2

**Comment by Free-Qi** [comment]
那么请问这个能提供源码供研究么。

**Comment by chenshuai2144** [comment]
pro 的 v2分支
